# Generated by Django 5.0.7 on 2024-08-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9999, unique=True)),
                ('slug', models.CharField(max_length=9999, unique=True)),
                ('img', models.CharField(max_length=9999)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('desc', models.TextField()),
                ('available', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categ')),
            ],
        ),
    ]
